### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by Pabloutndev** [pdepjm/2024-tp0-presentacion-Reichel-eze#1]
Hola Eze!, muy buena tu presentanción, un clasico los Brad o Tyler chads de la high school 🤣

Cómo sugerencia, podes añadir algún gusto musical o gastronomico. 
Podría ser alguna banda que estes escuchando ultimamente.

**Comment by Reichel-eze** [comment]
Jajaja, graciass. Dale, buenas sugerencias, las voy a estar agregando
